services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15
    container_name: cupping-auoc-postgres
    environment:
      POSTGRES_DB: cupping_auoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cupping_auoc"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - cupping-auoc-network

  # 后端API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: cupping-auoc-backend
    environment:
      ENVIRONMENT: production
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cupping_auoc
      SECRET_KEY: your-production-secret-key-change-this
      API_HOST: 0.0.0.0
      API_PORT: 8000
      ALLOWED_ORIGINS: http://localhost:3000,http://247lab.com.cn,https://247lab.com.cn,http://www.247lab.com.cn,https://www.247lab.com.cn

    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cupping-auoc-network

  # 前端 (Nginx)
  frontend:
    image: nginx:alpine
    container_name: cupping-auoc-frontend
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cupping-auoc-network

  # pgAdmin 数据库管理工具
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cupping-auoc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cupping-auoc.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      SCRIPT_NAME: /pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - cupping-auoc-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  cupping-auoc-network:
    driver: bridge 